version: '3'

services:
  portainer:
    container_name: portainer
    image: portainer/portainer
    volumes:
      - /home/$USER/docker_files/portainer/data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "9000:9000"
    network_mode: "host"
      
  mqtt:
    image: eclipse-mosquitto:latest
    container_name: "MQTT"
    restart: always
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - /home/$USER/docker_files/mqtt/data:/mosquitto/data
      - /home/$USER/docker_files/mqtt/config:/mosquitto/config
      - /home/$USER/docker_files/mqtt/log:/mosquitto/log
    network_mode: "host"
    
  home-assistant:
    image: homeassistant/home-assistant:latest
    container_name: "hass"
    restart: always
    depends_on:
      - mqtt
    ports:
      - "8123:8123"
    volumes:
      - /home/$USER/docker_files/homeassistant/config:/config
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
      - "/dev/ttyUSB1:/dev/ttyUSB1"
    network_mode: "host"